Feature/google api
Lambda-School-Labs/Labs26-StorySquad-DS-TeamB pull request #10
Opened 2020-09-17 19:17 UTC by Jwilson1172

# Description

This PR adds an OOP GoogleAPI service to the application. It also configures the endpoints in submission.py to provide text transcriptions and safe search moderation functionality.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [X] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [X] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings<sub>1</sub>
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

<sub>1</sub> - The class that is implemented in `project/app/utils/google_api.py` will throw an error and stop execution if no Google Credentials are provided in the environment variable GOOGLE_CREDS. the contents of this variable are the JSON in the service_account.json credential file that is downloaded from the Google Cloud Dashboard.

2020-09-17 23:08 UTC, lorischl-otter requested changes
Looks great overall! Just added in a few suggestions for changes & documentation updates. Also, I'm unclear on the `Change Status` vs `Has This Been Tested` boxes that are checked in the PR template. Could you change that so it's not a conflicting message of "Complete, but not tested" and "Yes" it has been tested? Thanks!

2020-09-17 23:08 UTC, lorischl-otter commented on notebooks/submission_endpoint_interations.ipynb
> +{
Could you add a couple lines at the top of this file to indicate its function? And add to the `notebooks` README a description as well, in the same formatting as the `utils` README? I think the more documentation we have, the easier it will be for anyone to follow along.

2020-09-17 23:08 UTC, lorischl-otter commented on project/app/api/submission.py
> +        story_id = story_id
Is this line (`story_id = story_id`) necessary?

2020-09-17 23:08 UTC, lorischl-otter commented on project/app/api/submission.py
> +    api and see's if the content is NSFW.
I'd suggest changing this second docstring line to something like:

"SafeSearch API and flags if explicit content detected."

2020-09-17 23:08 UTC, lorischl-otter commented on project/app/utils/google_api.py
> +from google.cloud import vision
Can you add a line of documentation about this file to the `utils` README?

2020-09-18 00:34 UTC, Jwilson1172 commented on project/app/api/submission.py
> +        story_id = story_id
not really it was supposed to be a stub for implementing the database call to store everything but I guess without that functionality it does seem kind of pointless to include.

2020-09-18 00:39 UTC, Jwilson1172 commented on notebooks/submission_endpoint_interations.ipynb
> +{
I feel like adding lines to the top of the notebook is a bit unnecessary with it's current header and `utils` entry. I'll go ahead and update the `utils` README with updated information about this file's functionality.

2020-09-18 01:03 UTC, Jwilson1172 commented
I also fixed the PR Description, I always assumed that one of the tested prompts was specific to unit-testing and one was specific to testing the functionality locally.

2020-09-18 01:18 UTC, schase15 approved these changes
Looks great so far! I appreciate the thoroughness of the docstrings.

2020-09-18 14:35 UTC, lorischl-otter commented on notebooks/submission_endpoint_interations.ipynb
> +{
Sounds good to me. Thanks

2020-09-18 14:35 UTC, lorischl-otter approved these changes
Thanks for the changes!

2020-09-18 14:36 UTC, lorischl-otter approved these changes
Thanks for the changes!

2020-09-18 14:36 UTC, merged