Adding spellcheck, confidence, transcribed notebooks, updated README
Lambda-School-Labs/Labs26-StorySquad-DS-TeamB pull request #23
Opened 2020-10-07 17:59 UTC by schase15

# Description

Added my notebooks for exploring spell checking, creating the confidence flag, and transcribing the given stories. I also updated the README of the notebooks folder to provide descriptions of each notebook.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [x] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2020-10-07 19:41 UTC, Jwilson1172 approved these changes, later dismissed

2020-10-07 20:06 UTC, lorischl-otter requested changes
Caught a small typo and requested a little bit more info in the README. Otherwise looks great. Thanks for getting these uploaded!

2020-10-07 20:06 UTC, lorischl-otter commented on notebooks/README.md
> +- `count_spelling_errors`: This notebook contains exploration of various spell check libraries and with the idea that it would help correct transcription errors. For the time being, we did not see en
Typo: "consistency"

2020-10-07 20:06 UTC, lorischl-otter commented on notebooks/README.md
> +- `count_spelling_errors`: This notebook contains exploration of various spell check libraries and with the idea that it would help correct transcription errors. For the time being, we did not see en
Can you include a little more on the spellcheck thoughts? Maybe something like: "to explore whether spell check could correct transcription errors, act as a metric for student writing, and/or increase the reliability of other metrics"

2020-10-07 20:32 UTC, schase15 commented on notebooks/README.md
> +- `count_spelling_errors`: This notebook contains exploration of various spell check libraries and with the idea that it would help correct transcription errors. For the time being, we did not see en
Fixed. Thank you!

2020-10-07 20:54 UTC, lorischl-otter approved these changes
Thanks for the updates!

2020-10-08 00:50 UTC, Jwilson1172 approved these changes

2020-10-08 00:50 UTC, merged